# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

"""
"""

import shutil
import typing as tp
from pathlib import Path

import mne
import pandas as pd

from neuralset.data import BaseData

from ..download import Osf
from ..utils import success_writer


class Luke2021(BaseData):
    subject: str

    # study/class level
    device: tp.ClassVar[str] = "Fnirs"
    url: tp.ClassVar[str] = "https://osf.io/f6tdk/"
    bibtex: tp.ClassVar[
        str
    ] = """
    @article{luke2021analysis,
    title={Analysis methods for measuring passive auditory fNIRS responses generated by a block-design paradigm},
    author={Luke, Robert and Larson, Eric and Shader, Maureen J and Innes-Brown, Hamish and Van Yper, Lindsey and Lee, Adrian KC and Sowman, Paul F and McAlpine, David},
    journal={Neurophotonics},
    volume={8},
    number={2},
    pages={025008--025008},
    year={2021},
    publisher={Society of Photo-Optical Instrumentation Engineers}
    }
    """
    doi: tp.ClassVar[str] = "doi:10.17605/OSF.IO/F6TDK"
    licence: tp.ClassVar[str] = "Unknown"
    description: tp.ClassVar[str] = "17 subjects exposed to noise or speech events."
    requirements: tp.ClassVar[tp.Tuple[str, ...]] = ("mne-nirs>=0.6.0",)

    _CODE_MAPPING: tp.ClassVar[dict[int, str]] = {
        1: "control",
        2: "noise",
        3: "speech",
        15: "start/end",
    }

    @classmethod
    def _download(cls, path: Path) -> None:
        Osf(study="f6tdk", dset_dir=path, folder="download").download()

        # Unzip fNIRS data
        from pyunpack import Archive

        dl_dir = path / "download"
        DATA_DIR_NAME = "2021-fNIRS-Analysis-Methods-Passive-Auditory"
        zip_file = dl_dir / (DATA_DIR_NAME + ".zip")
        with success_writer(zip_file) as already_done:
            if not already_done:
                Archive(str(zip_file)).extractall(str(dl_dir))

        # Move everything to parent folder and clean up
        shutil.move(dl_dir / DATA_DIR_NAME, dl_dir / "data")
        shutil.rmtree(dl_dir / "__MACOSX")
        # XXX Simplify directory name by removing "data" level

    @classmethod
    def _get_fname(cls, path: str | Path, subject: str) -> Path:
        subject = "sub-" + subject.zfill(2)
        return (
            Path(path)
            / "download"
            / "data"
            / subject
            / "ses-01"
            / "nirs"
            / f"{subject}_ses-01_task-AudioSpeechNoise_nirs.snirf"
        )

    @classmethod
    def _iter_timelines(cls, path: str | Path):
        """Returns a generator of all recordings"""
        for subject in range(1, 18):
            fname = cls._get_fname(path, str(subject))  # type: ignore[arg-type]
            assert fname.exists()
            yield cls(
                subject=str(subject),
                path=path,
            )  # type: ignore[arg-type]

    def _load_raw(self, timeline: str) -> mne.io.RawArray:
        fname = self._get_fname(self.path, self.subject)
        return mne.io.read_raw_snirf(fname)  # XXX Use BIDS instead?

    def _load_events(self) -> pd.DataFrame:
        raw = self._load_raw(self.timeline)
        events = pd.DataFrame(list(raw.annotations))
        events["start"] = events.onset

        events["type"] = "Stimulus"
        events["code"] = pd.to_numeric(events.description).astype(int)
        events["description"] = events.code.map(self._CODE_MAPPING)
        events = events[events.code != 15]  # Remove start/end of recording

        # Clean up dataframe
        events = events[["type", "start", "duration", "code", "description"]]

        uri = f"method:_load_raw?timeline={self.timeline}"
        fnirs = {"type": "Fnirs", "filepath": uri, "start": 0}
        events = pd.concat([pd.DataFrame([fnirs]), events])

        return events
