# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

import pickle
import time
import typing as tp
from pathlib import Path

import mne
import numpy as np
import pandas as pd
import pytest
import sklearn
import sklearn.preprocessing
import torch

import neuralset as ns
from neuralset.infra import ConfDict


@pytest.mark.parametrize("cls", (ns.features.Meg, ns.features.Fmri))
def test_neuro_pkl(cls: tp.Type[ns.features.BaseFeature]) -> None:
    inst = cls()
    string = pickle.dumps(inst)
    _ = pickle.loads(string)


def make_meg_event(filepath, start=0.0):
    timeline = "foo"
    if start == 0:
        timeline = "TestMeg2023_subject-0"
        filepath = f"method:_load_raw?timeline={timeline}"
    return dict(
        start=start,
        duration=99.99,
        timeline=timeline,
        filepath=filepath,
        type="Meg",
        subject="janedoe",
    )


def test_fmri(tmp_path: Path) -> None:
    # load study to create nii.gz files
    study = ns.data.StudyLoader(
        name="TestFmri2023",
        path=tmp_path / "data",
        n_timelines=1,
    ).build()

    timeline = "TestFmri2023_subject-0"
    event_manual = dict(
        start=0,
        duration=20.0,
        timeline=timeline,
        filepath=f"method:_load_raw?timeline={timeline}",
        type="Fmri",
        subject="janedoe",
        frequency=0.5,
    )
    feature = ns.features.Fmri(detrend=True)

    event_auto = study.query('type=="Fmri"').iloc[:1]
    event: tp.Any
    for event in (event_manual, event_auto):
        data = feature(event, start=0.0, duration=2.0).numpy()
        assert feature.frequency == "native", "Should be unmodified"
        assert np.array_equal(data.shape, [20, 20, 20, 1])
        assert data.max() > 0

    # fsaverage
    feature2 = ns.features.Fmri(
        mesh="fsaverage5", detrend=True, infra={"folder": tmp_path / "cache"}  # type: ignore
    )
    data = feature2(event, start=0.0, duration=20).numpy()
    assert np.array_equal(data.shape, [20484, 10])
    # stds should be 0 (no data) or close to 1 (reduced):
    stds = np.unique(np.std(data, axis=1))
    np.testing.assert_array_almost_equal(stds, [0] + [0.948] * (len(stds) - 1), decimal=3)
    # check that it's a memmap to avoid big memory issues:
    val = next(iter((feature2.infra.cache_dict._ram_data.values())))
    assert isinstance(val, np.memmap)

    # test from file
    nii = tmp_path / "data" / "sub-0.nii.gz"
    assert nii.exists()
    event["timeline"] = "foo"
    event["filepath"] = nii
    tdata = feature(event, start=0.0, duration=2.0)
    assert tdata.shape == torch.Size([20, 20, 20, 1])
    assert tdata.max() > 0


def test_meg(tmp_path: Path) -> None:
    cache_path = tmp_path / "cache"
    # test from study
    feature = ns.features.Meg(filter=(100, None))
    v = feature.infra.version
    assert v == "1"
    if ConfDict.UID_VERSION < 2:
        uid = f"neuralset.features.neuro.Meg._get_preprocessed_data,{v}/filter=[100,None]-845464f5"
    else:
        uid = f"neuralset.features.neuro.Meg._get_preprocessed_data,{v}/filter=[100,None]-460c3c1e"
    assert feature.infra.uid() == uid
    assert feature.frequency == "native"
    study = ns.data.StudyLoader(
        name="TestMeg2023", path=tmp_path / "data", n_timelines=1
    ).build()

    # check caching infra
    for cache in (None, cache_path):
        feature = ns.features.Meg(infra=dict(folder=cache))  # type: ignore
        meg_event = study.query('type=="Meg"').iloc[:1]
        feature(meg_event, start=0.0, duration=1.0)
    feature = ns.features.Meg(infra=dict(folder=cache_path))  # type: ignore
    feature.prepare(study)
    feature = ns.features.Meg(infra=dict(folder=cache_path), frequency=50.0)  # type: ignore
    feature.prepare(study)

    # test from file (.fif generated by TestMeg2023)
    fif = tmp_path / "data" / "sub-0-raw.fif"

    feature = ns.features.Meg()
    event = make_meg_event(fif, 0.0)
    data = feature(event, start=0.0, duration=1.0)
    assert feature._output_frequency(ns.events.Event.from_dict(event)) == 100.0  # type: ignore
    assert feature.frequency == "native"
    assert np.array_equal(data.shape, [20, 100])
    assert data.max() > 0.0

    # meg start > 0
    data = feature(make_meg_event(fif, start=0.5), start=0.0, duration=1.0)
    assert not any(data[:, 0])
    assert data[:, -1].max() > 0

    # meg start < 0
    data = feature(events=make_meg_event(fif, start=-1.0), start=0.0, duration=1.0)
    assert data.min() == 1

    # meg start < segment start
    data = feature(events=make_meg_event(fif, start=0.0), start=0.5, duration=1.0)
    assert data.min() == 0.5
    assert data.max() == 1.49

    # meg ends before end of segment
    event = make_meg_event(fif)
    data = feature(events=event, start=event["duration"] - 0.5, duration=1.0)
    assert not any(data[:, -1])
    assert data[:, 0].max() > 0

    # decim
    feature = ns.features.Meg(frequency=50.0)  # raw dependent
    data = feature(make_meg_event(fif, start=0.5), start=0.0, duration=1.0)
    assert np.array_equal(data.shape, [20, 50])
    assert not any(data[:, 0])
    assert data[:, -1].max() > 0

    # meg channels vary
    feature = ns.features.Meg(frequency=100.0)
    study = ns.data.StudyLoader(
        name="TestMeg2023", path=tmp_path / "data", n_timelines=2
    ).build()
    feature.prepare(study)
    images = study.query('type=="Image"')
    # select the first image of 2 different recordings
    sel = [d.index[0] for tl, d in images.groupby("timeline")]
    dset = ns.segments.iter_segments(
        study, idx=pd.Series(study.index.isin(sel)), start=0.0, duration=1.0
    )
    data_list = [feature(**seg.asdict()) for seg in dset]
    assert np.shape(data_list) == (2, len(feature._channels), 100)

    # test from file (.fif generated by TestMeg2023)
    assert fif.exists()
    events = pd.DataFrame(
        [
            dict(
                type="Meg",
                start=0.0,
                duration=100,
                filepath=fif,
                timeline="fo",
                subject="someonelse",
            ),
        ]
    )
    feature = ns.features.neuro.Meg(frequency=100.0)
    data = feature(events, start=10.0, duration=1.0)
    assert data.shape == torch.Size([20, 100])
    assert data.max() > 0


@pytest.mark.parametrize(
    "start,tmin,tmax",
    [
        [1.0, -0.2, -0.1],
        [2.0, 0.0, 0.3],
        [3.0, -0.1, 0.1],
        [4.0, -0.5, 2.0],
        [5.0, 0.1, 3.0],
        [6.0, 0.0, 4.0],
    ],
)
def test_meg_baseline(start: float, tmin: float, tmax: float, tmp_path: Path) -> None:
    ns.data.StudyLoader(name="TestMeg2023", path=tmp_path / "data", n_timelines=1).build()
    fif = tmp_path / "data" / "sub-0-raw.fif"

    sfreq = 100.0
    event_start = 0.0
    duration = 1.0
    event = make_meg_event(fif, start=event_start)

    # Extract window without baseline normalization
    feature = ns.features.Meg(frequency=sfreq, baseline=None)
    no_bl_data = feature(event, start=start, duration=duration)

    # Extract baseline only
    feature = ns.features.Meg(frequency=sfreq, baseline=None)
    bl_data = feature(event, start=start + tmin, duration=tmax - tmin)

    # Extract window with baseline normalization
    feature = ns.features.Meg(frequency=sfreq, baseline=(tmin, tmax))
    bl_norm_data = feature(event, start=start, duration=duration)

    # Extract larger window without baseline normalization
    feature = ns.features.Meg(frequency=sfreq, baseline=None)
    no_bl_full_data = feature(
        event, start=start + tmin, duration=max(duration, tmax) - tmin
    )

    # Ensure everything matches
    assert no_bl_data.shape == bl_norm_data.shape
    bl_len = int(sfreq * (tmax - tmin))
    assert bl_data.shape[1] == bl_len
    assert torch.allclose(bl_data, no_bl_full_data[:, :bl_len])
    bl_norm_data2 = no_bl_data - bl_data.mean(dim=1, keepdim=True)
    assert torch.allclose(bl_norm_data, bl_norm_data2)


def test_fnirs(tmp_path: Path) -> None:
    ns.data.StudyLoader(
        name="TestFnirs2024", path=tmp_path / "data", n_timelines=1
    ).build()

    sfreq = 10.0
    start = 0.0
    duration = 5.0

    timeline = "TestFnirs2024_subject-0"
    filepath = f"method:_load_raw?timeline={timeline}"
    event = dict(
        start=start,
        duration=99.99,
        timeline=timeline,
        filepath=filepath,
        type="Fnirs",
        subject="janedoe",
    )

    # Extract window without baseline normalization
    feature = ns.features.Fnirs(frequency=sfreq, baseline=None)
    data = feature(event, start=start, duration=duration)
    assert data.shape == (32, sfreq * duration)

    # Extract window with different preprocessing steps
    # XXX Uncomment preprocessing steps that require montage information (would need to update the
    # TestFnirs2024 class to also contain montage information)
    tmin, tmax = 0.0, 1.0
    feature = ns.features.Fnirs(
        frequency=sfreq,
        baseline=(tmin, tmax),
        # distance_threshold=10,
        # compute_optical_density=True,
        # scalp_coupling_index_threshold=0.0,
        # apply_tddr=True,
        # compute_heamo_response=True,
        # partial_pathlength_factor=0.1,
        # enhance_negative_correlation=True,
        filter=(0.01, 0.7),
    )
    preproc_data = feature(event, start=start, duration=duration)
    assert preproc_data.shape == (32, sfreq * duration)


def test_cache(tmp_path: Path) -> None:
    # FIXME the CACHE logic will fails if there are multiple recordings
    # (meg, fmri) within the same timeline.

    fmri: tp.Dict[str, tp.Any] = dict(
        device="Fmri",
        study="TestFmri2023",
        stim="Word",
        feature=ns.features.Fmri,
        duration=2.0,
        shape=(20, 20, 20, 1),
        file=tmp_path / "data" / "sub-0.nii.gz",
        subject="someone",
    )

    meg: tp.Dict[str, tp.Any] = dict(
        device="Meg",
        study="TestMeg2023",
        stim="Image",
        feature=ns.features.Meg,
        duration=0.5,
        shape=(20, 50),
        file=tmp_path / "data" / "sub-0-raw.fif",
        subject="someone",
    )

    for cond in (meg, fmri):
        study = str(cond["study"])
        events = ns.data.StudyLoader(name=study, path=tmp_path / "data").build()
        sel = events.type == cond["stim"]
        dset = ns.segments.list_segments(
            events, idx=sel, start=0.0, duration=cond["duration"]
        )
        segment = dset[0]

        for cache in (None, tmp_path / "cache"):
            for filtr in (None, (None, 20.0)):
                kwargs: tp.Any = dict(cache=cache, filter=filtr)
                # TODO, clean up when FMRI is dealt with
                kwargs.pop("cache")  # for now, now cache in FMRI
                if "Fmri" in study:
                    kwargs.pop("filter")
                if cond is meg:
                    kwargs["infra"] = {"folder": cache}

                feature = cond["feature"](**kwargs)
                data = feature(segment.events, segment.start, segment.duration)
                assert np.array_equal(data.shape, cond["shape"])
                assert data.max() > 0

        # no cache, no reader needed
        file = cond["file"]
        assert file.exists()
        event = dict(
            type=cond["device"],
            start=0.0,
            duration=cond["duration"],
            filepath=file,
            timeline="fo",
            subject="someone",
        )
        if cond["device"] == "Fmri":
            event.update(duration=20, frequency=0.5)
        events = pd.DataFrame(
            [
                dict(type="Word", start=10.0, duration=0.5, text="Hello", timeline="fo"),
                event,
            ]
        )
        feature = ns.features.base.Pulse(aggregation="sum")
        data = feature(events, start=10.0, duration=cond["duration"])
        assert np.array_equal(data.shape, [1])

        # no cache, but reader
        for cache in (None, tmp_path / "cache"):
            for filtr in (None, (None, 20.0)):
                kwargs = dict(cache=cache, filter=filtr)
                kwargs.pop("cache")  # TODO add fmri cache?
                if "Fmri" in cond["study"]:
                    kwargs.pop("filter")
                if cond is meg:
                    kwargs["infra"] = {"folder": cache}

                feature = cond["feature"](**kwargs)
                data = feature(events, start=0.0, duration=cond["duration"])
                assert np.array_equal(data.shape, cond["shape"])
                assert data.max() > 0


def test_meg_feature_cache(tmp_path: Path) -> None:
    events = ns.data.StudyLoader(name="TestMeg2023", path=tmp_path / "data").build()
    cache = tmp_path / "cache"
    feature = ns.features.Meg(
        frequency=100.0, filter=(None, 20.0), infra={"folder": cache}  # type: ignore
    )
    dset = ns.segments.list_segments(
        events, idx=events.type == "Image", start=0.0, duration=5
    )
    _ = feature(dset[0].events, start=dset[0].start, duration=dset[0].duration)
    v = feature.infra.version
    assert v == "1"
    path = cache / f"neuralset.features.neuro.Meg._get_preprocessed_data,{v}"
    if ConfDict.UID_VERSION == 1:
        path = path / "frequency=100,filter=[None,20]-0a52c3d4"
    else:
        path = path / "filter=[None,20],frequency=100-ad61abb8"
    assert path.exists(), f"Path does not exist, got: {list(path.parent.iterdir())}"
    content = [x.name for x in path.iterdir()]
    assert (
        len(content) == 6
    ), f"1 data file, 1 key file, and 3 yaml cfg files, 1 .cache_type: {content}"
    meg = next(feature.infra.cache_dict.values())  # type: ignore
    assert meg.preload is False


def test_base_meg(tmp_path: Path) -> None:
    feature = ns.features.Meg(
        frequency=100.0, filter=(None, 20.0), infra={"folder": tmp_path}  # type: ignore
    )
    assert isinstance(feature, ns.features.Meg)
    # check uids
    feature_keys = set(ConfDict.from_model(feature, uid=True).keys())
    assert feature_keys == {
        "name",
        "filter",
        "pick_types",
        "baseline",
        "frequency",
        "apply_proj",
        "offset",
        "scaler",
        "aggregation",
        "clamp",
        "apply_hilbert",
        "event_types",
        "infra",  # for version
    }


@pytest.mark.parametrize("apply_proj", (True, False))
def test_epoch_correct(apply_proj: bool) -> None:
    # download the first time
    events = ns.data.StudyLoader(name="MneSample2013", path=ns.CACHE_FOLDER).build()
    NUM = 12

    # Define segments
    segments = ns.segments.list_segments(
        events, idx=events.type == "Stimulus", start=0.0, duration=1.0
    )
    segments = segments[:NUM]
    dset = ns.SegmentDataset({"Meg": ns.features.Meg(apply_proj=apply_proj)}, segments)

    start = time.time()
    dloader = torch.utils.data.DataLoader(
        dset,
        collate_fn=dset.collate_fn,
        batch_size=len(dset),
    )
    batch = next(iter(dloader))
    timing = {"dataloader": time.time() - start}

    # Fast Mne reader
    start = time.time()
    meg_event = events.loc[events.type == "Meg"].iloc[0]
    stims = events.loc[events.type == "Stimulus"]
    stims = stims.iloc[:NUM, :]
    raw = ns.events.Meg.from_dict(meg_event).read()
    mne_events = np.ones((len(stims), 3), dtype=int)
    # print([s["start"] * raw.info["sfreq"] for s in segments])
    mne_events[:, 0] = stims.start * raw.info["sfreq"]
    raw = raw.pick(("meg",))
    epochs = mne.Epochs(
        raw, mne_events, tmin=0.0, tmax=1.0, baseline=None, proj=apply_proj
    )
    data = epochs.get_data()
    timing["epochs"] = time.time() - start

    # check for speed and correctness
    assert (
        timing["dataloader"] / timing["epochs"] < 15
    ), f"dataloader is too slow {timing}"
    meg = batch.data["Meg"].cpu().numpy()
    # np.testing.assert_almost_equal(meg * 10**12, data[:, :, :-1] * 10**12, decimal=3)
    np.testing.assert_almost_equal(meg / data[:, :, :-1], np.ones(meg.shape), decimal=3)


def test_channel_positions(tmp_path: Path) -> None:
    # Create and prepare Meg features
    meg = ns.features.Meg()
    study = ns.data.StudyLoader(
        name="TestMeg2023", path=tmp_path / "data", n_timelines=1
    ).build()
    meg.prepare(study)

    # Define and prepare channel positions feature
    invalid_value = ns.features.ChannelPositions.INVALID_VALUE
    ch_pos = ns.features.ChannelPositions(meg=meg)
    if ConfDict.UID_VERSION == 1:
        uid = "neuralset.features.neuro.ChannelPositions._get_channel_positions,0/meg={}-1acbca8d"
    else:
        uid = "neuralset.features.neuro.ChannelPositions._get_channel_positions,0/meg={}-d41d8cd9"
    assert ch_pos.infra.uid() == uid, "UID has changed (is it expected?)"
    ch_pos.prepare(study)

    event = ns.events.Event.from_dict(study[study.type == "Meg"].iloc[0])
    assert isinstance(event, ns.events.Meg)
    raw = next(meg._get_preprocessed_data([event]))
    positions = ch_pos(event, start=0.0, duration=1.0)
    assert positions.shape == (len(raw.ch_names), 2)
    assert (positions[raw.ch_names.index("INVALID_CHANNEL")] == invalid_value).all()


def test_meg_borders(tmp_path: Path) -> None:
    cache_path = tmp_path / "cache"
    # test from study
    feature = ns.features.Meg(frequency=100, filter=(100, None))
    loader = ns.data.StudyLoader(
        name="TestMeg2023", path=tmp_path / "data", n_timelines=1
    )
    events = loader.build()
    feature = ns.features.Meg(infra=dict(folder=cache_path))  # type: ignore
    meg_event = ns.events.Meg.from_dict(events.query('type=="Meg"').iloc[0])
    out = feature(meg_event, start=meg_event.start - 0.5, duration=1.0)
    # overlap with the beginning
    assert out[0, 0] == 0.0
    assert out[0, -1] != 0.0
    # overlap with the end
    out = feature(
        meg_event, start=meg_event.start + meg_event.duration - 0.5, duration=1.0
    )
    assert out[0, 0] != 0.0
    assert out[0, -1] == 0.0


@pytest.mark.parametrize("scaler", ["RobustScaler", "StandardScaler"])
@pytest.mark.parametrize("clamp", [None, 0.01, 0.1])
def test_scaled_meg(
    scaler: tp.Literal["RobustScaler", "StandardScaler"],
    tmp_path: Path,
    clamp: float | None,
) -> None:
    sfreq = 100.0
    start = 0.0
    duration = 1.0

    loader = ns.data.StudyLoader(
        name="TestMeg2023", path=tmp_path / "data", n_timelines=1
    )
    events = loader.build()
    event = ns.events.Meg.from_dict(events.query('type=="Meg"').iloc[0])

    feature = ns.features.Meg(frequency=sfreq)
    X = feature(event, start=start, duration=duration)

    raw = next(feature._get_preprocessed_data([event]))
    data = raw.load_data().get_data()

    _scaler = getattr(sklearn.preprocessing, scaler)().fit(data.T)

    scaled_feature = ns.features.Meg(
        frequency=sfreq,
        scaler=scaler,
        clamp=clamp,
    )
    scaled_X1 = scaled_feature(event, start=start, duration=duration)

    scaled_X2 = torch.Tensor(_scaler.transform(X.T).T)
    if clamp is not None:
        scaled_X2 = torch.clamp(scaled_X2, min=-clamp, max=clamp)

    assert torch.allclose(scaled_X1, scaled_X2, atol=1e-12)


def test_first_samp() -> None:
    events = ns.data.StudyLoader(name="MneSample2013", path=ns.CACHE_FOLDER).build()
    meg_event = ns.events.Event.from_dict(events.loc[events.type == "Meg"].iloc[0])
    assert meg_event.start > 0
    # first samp is ~6k at 150Hz, so start is at about 42s
    feature = ns.features.Meg(frequency=150)
    assert not feature(meg_event, 0, 1).norm()


def test_fast_event() -> None:
    events = ns.data.StudyLoader(name="MneSample2013", path=ns.CACHE_FOLDER).build()
    meg_event = ns.events.Event.from_dict(events.loc[events.type == "Meg"].iloc[0])
    assert meg_event.start > 0
    feature = ns.features.Meg(frequency=150)
    duration = 0.001
    assert feature(meg_event, start=meg_event.start + 1, duration=duration).norm()


def test_border_baseline(tmp_path: Path) -> None:
    events = ns.data.StudyLoader(name="TestMeg2023", path=tmp_path).build()
    meg_event = ns.events.Event.from_dict(events.loc[events.type == "Meg"].iloc[0])
    feature = ns.features.Meg(frequency=150, baseline=(0, 0.6))
    _ = feature(meg_event, meg_event.stop - 0.5, 1)  # baseline should not bug


def test_meg_method_on_infra(tmp_path: Path) -> None:
    events = ns.data.StudyLoader(name="TestMeg2023", path=tmp_path, n_timelines=1).build()
    infra: tp.Any = {"cluster": "local", "folder": tmp_path}
    feature = ns.features.Meg(frequency=150, baseline=(0, 0.6), infra=infra)
    feature.prepare(events)


class _PseudoNifti:  # hack used in nastase
    def __init__(self, data: np.ndarray) -> None:
        self.data = data
        self.shape = self.data.shape

    def get_fdata(self):
        return self.data


def test_fmri_mesh_from_2d() -> None:
    n_voxels = 40962 * 2  # fsaverage6
    n_times = 10
    nii = _PseudoNifti(np.random.rand(n_voxels, n_times))
    event = ns.events.Fmri(
        start=0,
        duration=n_times,
        frequency=1,
        timeline="foo",
        subject="blublu",
        filepath="blublu",
    )
    object.__setattr__(event, "read", lambda: nii)  # fake it
    feat = ns.features.Fmri(mesh="fsaverage5")
    out = feat(event, 0, 5)
    assert out.shape == (10242 * 2, 5)  # fsaverage5 size
